// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avwpsnpiucctywaplzse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2d3BzbnBpdWNjdHl3YXBsenNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3MDY1OTEsImV4cCI6MjA3NjI4MjU5MX0.zBFPNq4096WNI3aWsw9r8QC2IZTzzcIEnEXdDHmWCi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});